server:
  port: 8070
spring:
  application:
    name: notification
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, loggers
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true