server:
  port: 8070
spring:
  application:
    name: notification
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, loggers
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true