spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, loggers
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true