server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: 'root'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
logging:
  pattern:
    console: logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{uuid}] - %msg%n
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, loggers
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true